### ISSUE TITLE
Could you share the GoogleDrive link of the original pexels dataset?

### ISSUE THREAD

**Issue by Blddwkb** [janpf/self-supervised-multi-task-aesthetic-pretraining#5] opened 2022-03-07 17:20 UTC
First of all, thank you very much for making your excellent work available! It's very beneficial to me!
Could you share the GoogleDrive link of the original pexels dataset?
Because even if I use the shellscript(“download_pexels.sh”) you provide, the download speed is still slow. And I don't know the size of the dataset and whether my disk space is enough.
So I really hope to get your help. Thank you very much.

**Comment by Blddwkb** [comment] 2022-03-08 03:31
Sorry, I don't know much about shell commands. I deleted the ‘?w=1000’ in the shellscript, so the file size is the same as the original image, I will try again.

**Comment by janpf** [comment] 2022-08-02 09:28
Duplicate of #2 :)

**Closed as completed by janpf** 2022-08-02 09:28 UTC
